### ISSUE TITLE
Possible security issue

### ISSUE THREAD

**Issue by julesjanssen** [Naxon/laravel-url-uploaded-file#1]
Hey,

I'm not sure if it's the responsibility of this library, but accepting a URL from user input and handling the resulting file might have some security implications.

For example:
- the scheme might be something other than http/https
- the scheme might be missing
- the URL might point to something like `/etc/passwd`
- the URL might point to some internal URL which you don't want to expose (like the [AWS Instance Metadata endpoint](https://security.stackexchange.com/questions/219375/how-to-harden-against-credential-stealing-in-ec2-via-the-http-169-254-169-254))

Do you think checks / validations for the above points should / could be part of this library, or is that outside of its scope / responsibilities?

**Comment by Naxon** [comment]
Hey!

I created this package for a use case that didn't include receiving the URL from the user. The image that I needed to save from a URL is an image received from an API, so I pretty much knew what I'm going to get. I did add some basic checks, though, but no "heavy" validation was needed in my use case.

You're definitely right that additional checks and validations are required if the URL is received from a user, just like any other content received from users.

Learning from the past, I won't add any logic that I don't use myself to my packages as it makes them very hard to maintain, so I can only recommend to fork the repository or add validations in your project's scope before doing the actual upload.
